import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Badge from '#models/badge'

export default class extends BaseSeeder {
  async run() {
    // Supprimer les badges existants pour réinitialiser
    await Badge.query().delete()

    const badges = [
      // ========== BADGES DE DISTANCE ==========
      {
        code: 'distance_100km',
        name: 'Premiers pas',
        description: 'Parcourir 100 km au total',
        icon: '🥉',
        category: 'distance' as const,
        level: 1,
        conditionType: 'total_distance' as const,
        conditionValue: 100000, // 100 km en mètres
        sortOrder: 1,
      },
      {
        code: 'distance_500km',
        name: 'Explorateur',
        description: 'Parcourir 500 km au total',
        icon: '🥈',
        category: 'distance' as const,
        level: 2,
        conditionType: 'total_distance' as const,
        conditionValue: 500000,
        sortOrder: 2,
      },
      {
        code: 'distance_1000km',
        name: 'Voyageur',
        description: 'Parcourir 1 000 km au total',
        icon: '🥇',
        category: 'distance' as const,
        level: 3,
        conditionType: 'total_distance' as const,
        conditionValue: 1000000,
        sortOrder: 3,
      },
      {
        code: 'distance_2500km',
        name: 'Globe-trotter',
        description: 'Parcourir 2 500 km au total',
        icon: '💎',
        category: 'distance' as const,
        level: 4,
        conditionType: 'total_distance' as const,
        conditionValue: 2500000,
        sortOrder: 4,
      },
      {
        code: 'distance_5000km',
        name: 'Tour du monde',
        description: 'Parcourir 5 000 km au total',
        icon: '🌟',
        category: 'distance' as const,
        level: 5,
        conditionType: 'total_distance' as const,
        conditionValue: 5000000,
        sortOrder: 5,
      },
      {
        code: 'distance_10000km',
        name: 'Ultra-distance',
        description: 'Parcourir 10 000 km au total',
        icon: '👑',
        category: 'distance' as const,
        level: 6,
        conditionType: 'total_distance' as const,
        conditionValue: 10000000,
        sortOrder: 6,
      },

      // ========== BADGES D'ACTIVITÉS ==========
      {
        code: 'activities_10',
        name: 'Débutant',
        description: 'Enregistrer 10 activités',
        icon: '📊',
        category: 'activities' as const,
        level: 1,
        conditionType: 'total_activities' as const,
        conditionValue: 10,
        sortOrder: 11,
      },
      {
        code: 'activities_50',
        name: 'Motivé',
        description: 'Enregistrer 50 activités',
        icon: '📈',
        category: 'activities' as const,
        level: 2,
        conditionType: 'total_activities' as const,
        conditionValue: 50,
        sortOrder: 12,
      },
      {
        code: 'activities_100',
        name: 'Centurion',
        description: 'Enregistrer 100 activités',
        icon: '📉',
        category: 'activities' as const,
        level: 3,
        conditionType: 'total_activities' as const,
        conditionValue: 100,
        sortOrder: 13,
      },
      {
        code: 'activities_500',
        name: 'Marathonien',
        description: 'Enregistrer 500 activités',
        icon: '🎪',
        category: 'activities' as const,
        level: 4,
        conditionType: 'total_activities' as const,
        conditionValue: 500,
        sortOrder: 14,
      },
      {
        code: 'activities_1000',
        name: 'Légende',
        description: 'Enregistrer 1 000 activités',
        icon: '🏆',
        category: 'activities' as const,
        level: 5,
        conditionType: 'total_activities' as const,
        conditionValue: 1000,
        sortOrder: 15,
      },

      // ========== BADGES D'ÉLÉVATION ==========
      {
        code: 'elevation_5000m',
        name: 'Colline',
        description: 'Cumuler 5 000 m de dénivelé positif',
        icon: '🏔️',
        category: 'elevation' as const,
        level: 1,
        conditionType: 'total_elevation' as const,
        conditionValue: 5000,
        sortOrder: 21,
      },
      {
        code: 'elevation_10000m',
        name: 'Montagne',
        description: 'Cumuler 10 000 m de dénivelé positif',
        icon: '⛰️',
        category: 'elevation' as const,
        level: 2,
        conditionType: 'total_elevation' as const,
        conditionValue: 10000,
        sortOrder: 22,
      },
      {
        code: 'elevation_29000m',
        name: 'Everest',
        description: 'Cumuler 29 000 m de dénivelé positif (hauteur Everest)',
        icon: '🗻',
        category: 'elevation' as const,
        level: 3,
        conditionType: 'total_elevation' as const,
        conditionValue: 29000,
        sortOrder: 23,
      },
      {
        code: 'elevation_50000m',
        name: 'Vers les étoiles',
        description: 'Cumuler 50 000 m de dénivelé positif',
        icon: '✨',
        category: 'elevation' as const,
        level: 4,
        conditionType: 'total_elevation' as const,
        conditionValue: 50000,
        sortOrder: 24,
      },
      {
        code: 'elevation_100000m',
        name: 'Espace',
        description: 'Cumuler 100 000 m de dénivelé positif (limite espace)',
        icon: '🚀',
        category: 'elevation' as const,
        level: 5,
        conditionType: 'total_elevation' as const,
        conditionValue: 100000,
        sortOrder: 25,
      },

      // ========== BADGES DE RÉGULARITÉ ==========
      {
        code: 'streak_7days',
        name: 'Semaine parfaite',
        description: 'S\'entraîner 7 jours consécutifs',
        icon: '🔥',
        category: 'streak' as const,
        level: 1,
        conditionType: 'consecutive_days' as const,
        conditionValue: 7,
        sortOrder: 31,
      },
      {
        code: 'streak_30days',
        name: 'Marathonien de la régularité',
        description: 'S\'entraîner 30 jours consécutifs',
        icon: '🌈',
        category: 'streak' as const,
        level: 2,
        conditionType: 'consecutive_days' as const,
        conditionValue: 30,
        sortOrder: 32,
      },
      {
        code: 'streak_100days',
        name: 'Invincible',
        description: 'S\'entraîner 100 jours consécutifs',
        icon: '💪',
        category: 'streak' as const,
        level: 3,
        conditionType: 'consecutive_days' as const,
        conditionValue: 100,
        sortOrder: 33,
      },

      // ========== BADGES DE TEMPS ==========
      {
        code: 'time_10h',
        name: 'Première heure',
        description: 'Cumuler 10 heures d\'activité',
        icon: '⏱️',
        category: 'time' as const,
        level: 1,
        conditionType: 'total_time' as const,
        conditionValue: 36000, // 10h en secondes
        sortOrder: 41,
      },
      {
        code: 'time_50h',
        name: 'Marathon temps',
        description: 'Cumuler 50 heures d\'activité',
        icon: '⏰',
        category: 'time' as const,
        level: 2,
        conditionType: 'total_time' as const,
        conditionValue: 180000, // 50h
        sortOrder: 42,
      },
      {
        code: 'time_100h',
        name: 'Centurion du temps',
        description: 'Cumuler 100 heures d\'activité',
        icon: '🕐',
        category: 'time' as const,
        level: 3,
        conditionType: 'total_time' as const,
        conditionValue: 360000, // 100h
        sortOrder: 43,
      },
      {
        code: 'time_500h',
        name: 'Ultra-endurance',
        description: 'Cumuler 500 heures d\'activité',
        icon: '🕰️',
        category: 'time' as const,
        level: 4,
        conditionType: 'total_time' as const,
        conditionValue: 1800000, // 500h
        sortOrder: 44,
      },
      {
        code: 'time_1000h',
        name: 'Année complète',
        description: 'Cumuler 1 000 heures d\'activité',
        icon: '📅',
        category: 'time' as const,
        level: 5,
        conditionType: 'total_time' as const,
        conditionValue: 3600000, // 1000h
        sortOrder: 45,
      },

      // ========== BADGES SPÉCIAUX ==========
      {
        code: 'special_first_activity',
        name: 'Première sortie',
        description: 'Enregistrer votre première activité',
        icon: '🎉',
        category: 'special' as const,
        level: 1,
        conditionType: 'special' as const,
        conditionValue: null,
        sortOrder: 51,
      },
    ]

    await Badge.createMany(badges)

    console.log(`✅ ${badges.length} badges créés avec succès !`)
  }
}
