import { BaseSeeder } from '@adonisjs/lucid/seeders'
import PpgExercise from '#models/ppg_exercise'

export default class extends BaseSeeder {
  async run() {
    // Vérifier si les exercices par défaut existent déjà
    const existingCount = await PpgExercise.query().where('is_default', true).count('* as total')
    if (Number(existingCount[0].$extras.total) > 0) {
      console.log('Les exercices PPG par défaut existent déjà')
      return
    }

    const exercises = [
      // === JAMBES ===
      {
        name: 'Squats',
        category: 'jambes',
        description: 'Exercice fondamental pour les quadriceps et fessiers. Descendre en gardant le dos droit, genoux alignés avec les pieds.',
        targetMuscles: 'Quadriceps, fessiers, ischio-jambiers',
        difficulty: 'debutant',
        defaultReps: 15,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Fentes avant',
        category: 'jambes',
        description: 'Alterner les jambes en descendant le genou arrière vers le sol. Excellent pour l\'équilibre et la force unilatérale.',
        targetMuscles: 'Quadriceps, fessiers, mollets',
        difficulty: 'debutant',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Fentes latérales',
        category: 'jambes',
        description: 'Fentes sur le côté pour travailler les adducteurs et les stabilisateurs de hanche.',
        targetMuscles: 'Adducteurs, quadriceps, fessiers',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Squat jump',
        category: 'jambes',
        description: 'Squat explosif avec saut. Développe la puissance et la détente verticale.',
        targetMuscles: 'Quadriceps, fessiers, mollets',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Pistol squat',
        category: 'jambes',
        description: 'Squat sur une jambe. Exercice avancé requérant force et équilibre.',
        targetMuscles: 'Quadriceps, fessiers, stabilisateurs',
        difficulty: 'avance',
        defaultReps: 5,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Step-ups',
        category: 'jambes',
        description: 'Monter sur une marche ou un banc. Simule le mouvement de pédalage.',
        targetMuscles: 'Quadriceps, fessiers',
        difficulty: 'debutant',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Wall sit',
        category: 'jambes',
        description: 'Position assise contre un mur. Isométrique pour l\'endurance musculaire.',
        targetMuscles: 'Quadriceps, ischio-jambiers',
        difficulty: 'debutant',
        defaultDuration: '00:45',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Calf raises',
        category: 'jambes',
        description: 'Élévation sur la pointe des pieds pour renforcer les mollets.',
        targetMuscles: 'Mollets (gastrocnémiens, soléaires)',
        difficulty: 'debutant',
        defaultReps: 20,
        defaultSets: 3,
        isDefault: true,
      },

      // === CORE / GAINAGE ===
      {
        name: 'Planche',
        category: 'core',
        description: 'Position de gainage sur les avant-bras. Maintenir le corps aligné.',
        targetMuscles: 'Abdominaux, lombaires, transverse',
        difficulty: 'debutant',
        defaultDuration: '00:45',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Planche latérale',
        category: 'core',
        description: 'Gainage sur le côté pour travailler les obliques.',
        targetMuscles: 'Obliques, transverse',
        difficulty: 'intermediaire',
        defaultDuration: '00:30',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Crunch',
        category: 'core',
        description: 'Contraction abdominale classique. Décoller uniquement les épaules du sol.',
        targetMuscles: 'Grands droits abdominaux',
        difficulty: 'debutant',
        defaultReps: 20,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Bicycle crunch',
        category: 'core',
        description: 'Crunch avec rotation, coude vers genou opposé. Excellent pour les obliques.',
        targetMuscles: 'Abdominaux, obliques',
        difficulty: 'intermediaire',
        defaultReps: 15,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Mountain climbers',
        category: 'core',
        description: 'Genoux alternés vers la poitrine en position de planche. Travail cardio + core.',
        targetMuscles: 'Abdominaux, fléchisseurs de hanche',
        difficulty: 'intermediaire',
        defaultDuration: '00:30',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Russian twist',
        category: 'core',
        description: 'Rotation du buste avec les mains ou un poids. Assis, pieds décollés.',
        targetMuscles: 'Obliques, transverse',
        difficulty: 'intermediaire',
        defaultReps: 20,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Dead bug',
        category: 'core',
        description: 'Allongé sur le dos, étendre bras et jambe opposés. Stabilisation profonde.',
        targetMuscles: 'Transverse, lombaires',
        difficulty: 'debutant',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Superman',
        category: 'core',
        description: 'Allongé sur le ventre, lever bras et jambes simultanément. Renforce le dos.',
        targetMuscles: 'Érecteurs du rachis, fessiers',
        difficulty: 'debutant',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Hollow body hold',
        category: 'core',
        description: 'Position creuse sur le dos, jambes et épaules décollées. Gainage intense.',
        targetMuscles: 'Abdominaux profonds',
        difficulty: 'avance',
        defaultDuration: '00:30',
        defaultSets: 3,
        isDefault: true,
      },

      // === BRAS / HAUT DU CORPS ===
      {
        name: 'Pompes',
        category: 'bras',
        description: 'Exercice fondamental pour le haut du corps. Variante sur genoux pour débutants.',
        targetMuscles: 'Pectoraux, triceps, deltoïdes',
        difficulty: 'debutant',
        defaultReps: 15,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Pompes diamant',
        category: 'bras',
        description: 'Pompes avec mains rapprochées formant un diamant. Accent sur les triceps.',
        targetMuscles: 'Triceps, pectoraux',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Dips sur chaise',
        category: 'bras',
        description: 'Triceps dips avec appui sur une chaise ou un banc.',
        targetMuscles: 'Triceps, deltoïdes antérieurs',
        difficulty: 'debutant',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Pike push-ups',
        category: 'bras',
        description: 'Pompes en V inversé pour cibler les épaules.',
        targetMuscles: 'Deltoïdes, triceps',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Rowing inversé',
        category: 'bras',
        description: 'Tirage horizontal sous une barre ou table basse. Renforce le dos.',
        targetMuscles: 'Dorsaux, biceps, rhomboïdes',
        difficulty: 'intermediaire',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },

      // === CARDIO ===
      {
        name: 'Burpees',
        category: 'cardio',
        description: 'Exercice complet : squat, pompe, saut. Intense et efficace.',
        targetMuscles: 'Corps entier',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Jumping jacks',
        category: 'cardio',
        description: 'Sauts en étoile. Échauffement ou travail cardio léger.',
        targetMuscles: 'Corps entier',
        difficulty: 'debutant',
        defaultDuration: '00:45',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'High knees',
        category: 'cardio',
        description: 'Course sur place avec genoux hauts. Travail cardiovasculaire.',
        targetMuscles: 'Fléchisseurs de hanche, cardio',
        difficulty: 'debutant',
        defaultDuration: '00:30',
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Box jumps',
        category: 'cardio',
        description: 'Sauts sur une boîte ou marche. Puissance et explosivité.',
        targetMuscles: 'Quadriceps, fessiers, mollets',
        difficulty: 'intermediaire',
        defaultReps: 10,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Skaters',
        category: 'cardio',
        description: 'Sauts latéraux d\'une jambe à l\'autre. Travail d\'équilibre et cardio.',
        targetMuscles: 'Abducteurs, quadriceps',
        difficulty: 'intermediaire',
        defaultReps: 12,
        defaultSets: 3,
        isDefault: true,
      },
      {
        name: 'Tuck jumps',
        category: 'cardio',
        description: 'Sauts avec genoux ramenés vers la poitrine. Explosivité maximale.',
        targetMuscles: 'Quadriceps, abdominaux',
        difficulty: 'avance',
        defaultReps: 8,
        defaultSets: 3,
        isDefault: true,
      },
    ]

    await PpgExercise.createMany(exercises as any)
    console.log(`${exercises.length} exercices PPG par défaut créés`)
  }
}
